
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "basic" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: navigate to directory
      run: cd basic
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag basic:$(date +%s) . 
    - name: Push Docker image
      run: docker push basic:$(date +%s)