
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "basic" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: navigate to directory
      run: cd basic
    - name: Build Docker image
      run: docker build ./api/ -t troinux/master_docker.io:latest-basic
    - name: Push Docker images
      run: |
         docker login -u ${{secrets.DOCKER_HUB_ACTOR}} -p ${{secrets.API_KEY_DOCKER_HUB}}
         docker push ${{secrets.DOCKER_HUB_ACTOR}}/master_docker.io:latest-basic
