
name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Sanitize tag
        id: sanitize
        run: | 
         TAG=${GITHUB_REF##*/}
         TAG=${GITHUB_REF##*/} 
         TAG=${TAG//[^a-zA-Z0-9\_\-\.]/} 
         echo "::set-output name=tag::$TAG"  
         
      - name: Checkout repo to container
        uses: actions/checkout@v4
        
      - name: navigate to directory
        run: |
          cd basic
          echo "Navigated to ${pwd}"
          ls -a
          
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub 
        uses: docker/login-action@v1 
        if: github.event_name != 'pull_request'
        with: 
         username: ${{ secrets.DOCKER_HUB_ACTOR }} 
         password: ${{ secrets.API_KEY_DOCKER_HUB}}
          
      - name: Build and push Docker image 
        uses: docker/build-push-action@v2 
        if: github.event_name != 'pull_request'
        with: 
          context: ./basic
          push: true 
          tags:  ${{ secrets.DOCKER_HUB_ACTOR }}/${{ secrets.REGISTRY }}:${{ steps.sanitize.outputs.tag }}

      
      
