
name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo to container
        uses: actions/checkout@v4
      - name: Log into registry ${{ secrets.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_ACTOR }}
          password: ${{ secrets.API_KEY_DOCKER_HUB }}
          
      - name: navigate to directory
        run: cd basic
      - name: Build Docker image
        run: docker build . -t troinux/master_docker.io:latest-basic
      - name: Push Docker images
        run: |
          docker login -u ${{secrets.DOCKER_HUB_ACTOR}} -p ${{secrets.API_KEY_DOCKER_HUB}}
          docker push ${{secrets.DOCKER_HUB_ACTOR}}/master_docker.io:latest-basic
