
name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Sanitize tag
        id: sanitize
        run: | 
         TAG=${GITHUB_REF##*/} 
         TAG=${TAG//[^a-zA-Z0-9\_\-\.]/} 
         echo "::set-output name=tag::$TAG"  
         
      - name: Checkout repo to container
        uses: actions/checkout@v4
      - name: navigate to directory
        run: |
          cd basic
          echo "Navigated to ${pwd}"
          ls -a
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1
         
      # - name: Log into registry ${{ secrets.REGISTRY }}
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      #   if: github.event_name != 'pull_request'
      #   with:
      #     registry: ${{ secrets.REGISTRY }}
      #     username: ${{ secrets.DOCKER_HUB_ACTOR }}
      #     password: ${{ secrets.API_KEY_DOCKER_HUB }}
          
      - name: Build and push Docker image 
        uses: docker/build-push-action@v2 
        with: 
          context: . 
          push: true 
          tags:  ${{ secrets.DOCKER_HUB_ACTOR }}/${{ secrets.REGISTRY }}:${{ steps.sanitize.outputs.tag }}

      
      # - name: Build Docker image
      #   run: docker build . -t ${{ secrets.API_KEY_DOCKER_HUB }}/master_docker.io:latest-basic
      # - name: Push Docker images
      #   run: |
      #     docker login -u ${{secrets.DOCKER_HUB_ACTOR}} -p ${{secrets.API_KEY_DOCKER_HUB}}
      #     docker push ${{secrets.DOCKER_HUB_ACTOR}}/master_docker.io:latest-basic
